/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/create`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pdf-status` | `/pdf-status`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/atividade/create/[cronogramaId]`, params: Router.UnknownInputParams & { cronogramaId: string | number; } } | { pathname: `/atividade/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/atividades/[cronogramaId]`, params: Router.UnknownInputParams & { cronogramaId: string | number; } } | { pathname: `/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/preview/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/create`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pdf-status` | `/pdf-status`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/atividade/create/[cronogramaId]`, params: Router.UnknownOutputParams & { cronogramaId: string; } } | { pathname: `/atividade/edit/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/atividades/[cronogramaId]`, params: Router.UnknownOutputParams & { cronogramaId: string; } } | { pathname: `/edit/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/preview/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/create${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pdf-status${`?${string}` | `#${string}` | ''}` | `/pdf-status${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/create`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pdf-status` | `/pdf-status`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/atividade/create/${Router.SingleRoutePart<T>}` | `/atividade/edit/${Router.SingleRoutePart<T>}` | `/atividades/${Router.SingleRoutePart<T>}` | `/edit/${Router.SingleRoutePart<T>}` | `/preview/${Router.SingleRoutePart<T>}` | { pathname: `/atividade/create/[cronogramaId]`, params: Router.UnknownInputParams & { cronogramaId: string | number; } } | { pathname: `/atividade/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/atividades/[cronogramaId]`, params: Router.UnknownInputParams & { cronogramaId: string | number; } } | { pathname: `/edit/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/preview/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
